version: '3.9'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=mypassword
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mydatabase:5432/data  # Update database connection URL
      - SPRING_DATASOURCE_USERNAME=test  # Update username
      - SPRING_DATASOURCE_PASSWORD=mypassword  # Update password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mydatabase
    restart: on-failure

  mydatabase:
    build:
      context: ./database
      dockerfile: Dockerfile
    # container_name: mydatabase
    ports:
      - "5432:5432"  # Map container port 5432 to host port 5432
    environment:
      - POSTGRES_DB=data
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=mypassword